/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Acceuil (void);
GtkWidget* create_Ajouter (void);
GtkWidget* create_Suppresion (void);
GtkWidget* create_chercher (void);
GtkWidget* create_Afficher (void);
GtkWidget* create_Dashboard (void);
GtkWidget* create_Home (void);
GtkWidget* create_window1 (void);
GtkWidget* create_Authentification_foyer (void);
