/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Acceuil (void)
{
  GtkWidget *Acceuil;
  GtkWidget *fixed1;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *image6;
  GtkWidget *Supprimer1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label81;
  GtkWidget *Ajouter;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label83;
  GtkWidget *_modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label82;
  GtkWidget *Quitter;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label85;
  GtkWidget *Agent_de_foyer;
  GtkWidget *Chercher;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label84;
  GtkWidget *Afficher;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image26;
  GtkWidget *label124;
  GtkWidget *Dashboard;

  Acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Acceuil), _("Acceuil"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Acceuil), fixed1);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 40, 280);
  gtk_widget_set_size_request (vseparator1, 16, 16);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator2, 64, 152);
  gtk_widget_set_size_request (vseparator2, 16, 16);

  image6 = create_pixmap (Acceuil, "PHOf76c9c34-6e70-11e5-8e72-dafe53665b28-805x453.jpg");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed1), image6, 16, 0);
  gtk_widget_set_size_request (image6, 1032, 416);

  Supprimer1 = gtk_button_new ();
  gtk_widget_show (Supprimer1);
  gtk_fixed_put (GTK_FIXED (fixed1), Supprimer1, 608, 456);
  gtk_widget_set_size_request (Supprimer1, 136, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Supprimer1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("<span color=\"red\"> Supprimer</span>"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox1), label81, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label81), TRUE);

  Ajouter = gtk_button_new ();
  gtk_widget_show (Ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), Ajouter, 336, 456);
  gtk_widget_set_size_request (Ajouter, 144, 45);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Ajouter), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox3), label83, FALSE, FALSE, 0);

  _modifier = gtk_button_new ();
  gtk_widget_show (_modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), _modifier, 336, 568);
  gtk_widget_set_size_request (_modifier, 144, 45);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (_modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label82 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label82);
  gtk_box_pack_start (GTK_BOX (hbox2), label82, FALSE, FALSE, 0);

  Quitter = gtk_button_new ();
  gtk_widget_show (Quitter);
  gtk_fixed_put (GTK_FIXED (fixed1), Quitter, 488, 640);
  gtk_widget_set_size_request (Quitter, 112, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Quitter), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("<span color=\"black\"> Quitter</span>"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox5), label85, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label85), TRUE);

  Agent_de_foyer = gtk_label_new (_("<span color=\"green\"> Agent de foyer</span>"));
  gtk_widget_show (Agent_de_foyer);
  gtk_fixed_put (GTK_FIXED (fixed1), Agent_de_foyer, 352, 408);
  gtk_widget_set_size_request (Agent_de_foyer, 360, 48);
  gtk_label_set_use_markup (GTK_LABEL (Agent_de_foyer), TRUE);

  Chercher = gtk_button_new ();
  gtk_widget_show (Chercher);
  gtk_fixed_put (GTK_FIXED (fixed1), Chercher, 608, 512);
  gtk_widget_set_size_request (Chercher, 136, 45);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Chercher), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox4), label84, FALSE, FALSE, 0);

  Afficher = gtk_button_new ();
  gtk_widget_show (Afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), Afficher, 336, 512);
  gtk_widget_set_size_request (Afficher, 144, 45);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (Afficher), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image26 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox16), image26, FALSE, FALSE, 0);

  label124 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label124);
  gtk_box_pack_start (GTK_BOX (hbox16), label124, FALSE, FALSE, 0);

  Dashboard = gtk_button_new_with_mnemonic (_("Dashboard"));
  gtk_widget_show (Dashboard);
  gtk_fixed_put (GTK_FIXED (fixed1), Dashboard, 608, 568);
  gtk_widget_set_size_request (Dashboard, 136, 45);

  g_signal_connect ((gpointer) Supprimer1, "clicked",
                    G_CALLBACK (on_Supprimer1_clicked),
                    NULL);
  g_signal_connect ((gpointer) Ajouter, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) _modifier, "clicked",
                    G_CALLBACK (on__modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) Quitter, "clicked",
                    G_CALLBACK (on_Quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) Chercher, "clicked",
                    G_CALLBACK (on_Chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) Afficher, "clicked",
                    G_CALLBACK (on_Afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) Dashboard, "clicked",
                    G_CALLBACK (on_Dashboard_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Acceuil, Acceuil, "Acceuil");
  GLADE_HOOKUP_OBJECT (Acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Acceuil, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (Acceuil, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (Acceuil, image6, "image6");
  GLADE_HOOKUP_OBJECT (Acceuil, Supprimer1, "Supprimer1");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (Acceuil, label81, "label81");
  GLADE_HOOKUP_OBJECT (Acceuil, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Acceuil, image4, "image4");
  GLADE_HOOKUP_OBJECT (Acceuil, label83, "label83");
  GLADE_HOOKUP_OBJECT (Acceuil, _modifier, "_modifier");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Acceuil, image3, "image3");
  GLADE_HOOKUP_OBJECT (Acceuil, label82, "label82");
  GLADE_HOOKUP_OBJECT (Acceuil, Quitter, "Quitter");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Acceuil, image7, "image7");
  GLADE_HOOKUP_OBJECT (Acceuil, label85, "label85");
  GLADE_HOOKUP_OBJECT (Acceuil, Agent_de_foyer, "Agent_de_foyer");
  GLADE_HOOKUP_OBJECT (Acceuil, Chercher, "Chercher");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Acceuil, image5, "image5");
  GLADE_HOOKUP_OBJECT (Acceuil, label84, "label84");
  GLADE_HOOKUP_OBJECT (Acceuil, Afficher, "Afficher");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Acceuil, image26, "image26");
  GLADE_HOOKUP_OBJECT (Acceuil, label124, "label124");
  GLADE_HOOKUP_OBJECT (Acceuil, Dashboard, "Dashboard");

  return Acceuil;
}

GtkWidget*
create_Ajouter (void)
{
  GtkWidget *Ajouter;
  GtkWidget *fixed2;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkWidget *entry_cin;
  GtkWidget *entry_id;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *ID;
  GtkWidget *Pr__nom;
  GtkWidget *CIN;
  GtkWidget *Nom;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *mail;
  GtkWidget *label119;
  GtkWidget *hobbies;
  GtkWidget *Homme;
  GSList *Homme_group = NULL;
  GtkWidget *Femme;
  GtkWidget *combobox2;
  GtkWidget *Niveau;
  GtkWidget *Sexe;
  GtkWidget *label120;
  GtkWidget *Date_de_naissance;
  GtkWidget *JJ;
  GtkWidget *MM;
  GtkWidget *AA;
  GtkWidget *etat;
  GtkWidget *Natation;
  GtkWidget *lec;
  GtkWidget *entry37;
  GtkWidget *prog;
  GtkWidget *autre;
  GtkWidget *label95;
  GtkWidget *Ajouter2;
  GtkWidget *Annuler1;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image14;
  GtkWidget *label86;
  GtkWidget *entry38;
  GtkWidget *label136;
  GtkWidget *Homeajout;
  GtkWidget *image10;
  GtkWidget *image31;

  Ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajouter), fixed2);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nom, 112, 56);
  gtk_widget_set_size_request (entry_nom, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_prenom, 456, 56);
  gtk_widget_set_size_request (entry_prenom, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  entry_cin = gtk_entry_new ();
  gtk_widget_show (entry_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_cin, 112, 120);
  gtk_widget_set_size_request (entry_cin, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin), 8226);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id, 456, 120);
  gtk_widget_set_size_request (entry_id, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 256, 272);
  gtk_widget_set_size_request (spinbutton1, 64, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 360, 272);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 456, 272);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  ID = gtk_label_new (_("ID"));
  gtk_widget_show (ID);
  gtk_fixed_put (GTK_FIXED (fixed2), ID, 376, 128);
  gtk_widget_set_size_request (ID, 49, 17);

  Pr__nom = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (Pr__nom);
  gtk_fixed_put (GTK_FIXED (fixed2), Pr__nom, 360, 64);
  gtk_widget_set_size_request (Pr__nom, 64, 17);

  CIN = gtk_label_new (_("CIN"));
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed2), CIN, 32, 128);
  gtk_widget_set_size_request (CIN, 49, 17);

  Nom = gtk_label_new (_("Nom"));
  gtk_widget_show (Nom);
  gtk_fixed_put (GTK_FIXED (fixed2), Nom, 32, 64);
  gtk_widget_set_size_request (Nom, 49, 17);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed2), entry27, 112, 176);
  gtk_widget_set_size_request (entry27, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed2), entry28, 456, 176);
  gtk_widget_set_size_request (entry28, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  mail = gtk_label_new (_("E-Mail"));
  gtk_widget_show (mail);
  gtk_fixed_put (GTK_FIXED (fixed2), mail, 24, 192);
  gtk_widget_set_size_request (mail, 57, 17);

  label119 = gtk_label_new (_("N\302\260 Telephone"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed2), label119, 352, 184);
  gtk_widget_set_size_request (label119, 104, 17);

  hobbies = gtk_label_new (_("hobbies"));
  gtk_widget_show (hobbies);
  gtk_fixed_put (GTK_FIXED (fixed2), hobbies, 88, 464);
  gtk_widget_set_size_request (hobbies, 80, 17);

  Homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (Homme);
  gtk_fixed_put (GTK_FIXED (fixed2), Homme, 208, 416);
  gtk_widget_set_size_request (Homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Homme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Homme));

  Femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (Femme);
  gtk_fixed_put (GTK_FIXED (fixed2), Femme, 384, 416);
  gtk_widget_set_size_request (Femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Femme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Femme));

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox2, 136, 328);
  gtk_widget_set_size_request (combobox2, 112, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("1er"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("2eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("3eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("4eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("5eme"));

  Niveau = gtk_label_new (_("Niveau"));
  gtk_widget_show (Niveau);
  gtk_fixed_put (GTK_FIXED (fixed2), Niveau, 80, 344);
  gtk_widget_set_size_request (Niveau, 49, 17);

  Sexe = gtk_label_new (_("Sexe"));
  gtk_widget_show (Sexe);
  gtk_fixed_put (GTK_FIXED (fixed2), Sexe, 112, 424);
  gtk_widget_set_size_request (Sexe, 49, 17);

  label120 = gtk_label_new (_("<span color=\"red\">Bienvenue \303\240 l'espace Ajout</span>"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed2), label120, 56, 8);
  gtk_widget_set_size_request (label120, 240, 33);
  gtk_label_set_use_markup (GTK_LABEL (label120), TRUE);

  Date_de_naissance = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (Date_de_naissance);
  gtk_fixed_put (GTK_FIXED (fixed2), Date_de_naissance, 8, 272);
  gtk_widget_set_size_request (Date_de_naissance, 176, 25);

  JJ = gtk_label_new (_("JJ"));
  gtk_widget_show (JJ);
  gtk_fixed_put (GTK_FIXED (fixed2), JJ, 216, 272);
  gtk_widget_set_size_request (JJ, 48, 25);

  MM = gtk_label_new (_("MM"));
  gtk_widget_show (MM);
  gtk_fixed_put (GTK_FIXED (fixed2), MM, 320, 272);
  gtk_widget_set_size_request (MM, 48, 25);

  AA = gtk_label_new (_("AA"));
  gtk_widget_show (AA);
  gtk_fixed_put (GTK_FIXED (fixed2), AA, 424, 272);
  gtk_widget_set_size_request (AA, 40, 24);

  etat = gtk_label_new (_("Etat financier"));
  gtk_widget_show (etat);
  gtk_fixed_put (GTK_FIXED (fixed2), etat, 360, 336);
  gtk_widget_set_size_request (etat, 104, 25);

  Natation = gtk_check_button_new_with_mnemonic (_("Natation"));
  gtk_widget_show (Natation);
  gtk_fixed_put (GTK_FIXED (fixed2), Natation, 208, 456);
  gtk_widget_set_size_request (Natation, 118, 24);

  lec = gtk_check_button_new_with_mnemonic (_("Lecture"));
  gtk_widget_show (lec);
  gtk_fixed_put (GTK_FIXED (fixed2), lec, 384, 456);
  gtk_widget_set_size_request (lec, 118, 24);

  entry37 = gtk_entry_new ();
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed2), entry37, 464, 336);
  gtk_widget_set_size_request (entry37, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  prog = gtk_check_button_new_with_mnemonic (_("programmation"));
  gtk_widget_show (prog);
  gtk_fixed_put (GTK_FIXED (fixed2), prog, 208, 496);
  gtk_widget_set_size_request (prog, 144, 24);

  autre = gtk_check_button_new_with_mnemonic (_("autre"));
  gtk_widget_show (autre);
  gtk_fixed_put (GTK_FIXED (fixed2), autre, 384, 496);
  gtk_widget_set_size_request (autre, 118, 24);

  label95 = gtk_label_new ("");
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed2), label95, 184, 536);
  gtk_widget_set_size_request (label95, 352, 48);

  Ajouter2 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (Ajouter2);
  gtk_fixed_put (GTK_FIXED (fixed2), Ajouter2, 272, 592);
  gtk_widget_set_size_request (Ajouter2, 144, 37);

  Annuler1 = gtk_button_new ();
  gtk_widget_show (Annuler1);
  gtk_fixed_put (GTK_FIXED (fixed2), Annuler1, 464, 592);
  gtk_widget_set_size_request (Annuler1, 112, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (Annuler1), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox7), image14, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox7), label86, FALSE, FALSE, 0);

  entry38 = gtk_entry_new ();
  gtk_widget_show (entry38);
  gtk_fixed_put (GTK_FIXED (fixed2), entry38, 112, 232);
  gtk_widget_set_size_request (entry38, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry38), 8226);

  label136 = gtk_label_new (_("adresse"));
  gtk_widget_show (label136);
  gtk_fixed_put (GTK_FIXED (fixed2), label136, 16, 232);
  gtk_widget_set_size_request (label136, 80, 25);

  Homeajout = gtk_button_new ();
  gtk_widget_show (Homeajout);
  gtk_fixed_put (GTK_FIXED (fixed2), Homeajout, 600, 592);
  gtk_widget_set_size_request (Homeajout, 64, 37);

  image10 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (Homeajout), image10);

  image31 = create_pixmap (Ajouter, "261987093_446844177019898_7288770172409585199_n (1).jpg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed2), image31, 632, 16);
  gtk_widget_set_size_request (image31, 472, 576);

  g_signal_connect ((gpointer) Homme, "toggled",
                    G_CALLBACK (on_Homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) Femme, "toggled",
                    G_CALLBACK (on_Femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) Natation, "toggled",
                    G_CALLBACK (on_Natation_toggled),
                    NULL);
  g_signal_connect ((gpointer) lec, "toggled",
                    G_CALLBACK (on_lec_toggled),
                    NULL);
  g_signal_connect ((gpointer) prog, "toggled",
                    G_CALLBACK (on_prog_toggled),
                    NULL);
  g_signal_connect ((gpointer) autre, "toggled",
                    G_CALLBACK (on_autre_toggled),
                    NULL);
  g_signal_connect ((gpointer) Ajouter2, "clicked",
                    G_CALLBACK (on_Ajouter2_clicked),
                    NULL);
  g_signal_connect ((gpointer) Annuler1, "clicked",
                    G_CALLBACK (on_Annuler1_clicked),
                    NULL);
  g_signal_connect ((gpointer) Homeajout, "clicked",
                    G_CALLBACK (on_Homeajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_cin, "entry_cin");
  GLADE_HOOKUP_OBJECT (Ajouter, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Ajouter, ID, "ID");
  GLADE_HOOKUP_OBJECT (Ajouter, Pr__nom, "Pr__nom");
  GLADE_HOOKUP_OBJECT (Ajouter, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (Ajouter, Nom, "Nom");
  GLADE_HOOKUP_OBJECT (Ajouter, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (Ajouter, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (Ajouter, mail, "mail");
  GLADE_HOOKUP_OBJECT (Ajouter, label119, "label119");
  GLADE_HOOKUP_OBJECT (Ajouter, hobbies, "hobbies");
  GLADE_HOOKUP_OBJECT (Ajouter, Homme, "Homme");
  GLADE_HOOKUP_OBJECT (Ajouter, Femme, "Femme");
  GLADE_HOOKUP_OBJECT (Ajouter, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (Ajouter, Niveau, "Niveau");
  GLADE_HOOKUP_OBJECT (Ajouter, Sexe, "Sexe");
  GLADE_HOOKUP_OBJECT (Ajouter, label120, "label120");
  GLADE_HOOKUP_OBJECT (Ajouter, Date_de_naissance, "Date_de_naissance");
  GLADE_HOOKUP_OBJECT (Ajouter, JJ, "JJ");
  GLADE_HOOKUP_OBJECT (Ajouter, MM, "MM");
  GLADE_HOOKUP_OBJECT (Ajouter, AA, "AA");
  GLADE_HOOKUP_OBJECT (Ajouter, etat, "etat");
  GLADE_HOOKUP_OBJECT (Ajouter, Natation, "Natation");
  GLADE_HOOKUP_OBJECT (Ajouter, lec, "lec");
  GLADE_HOOKUP_OBJECT (Ajouter, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (Ajouter, prog, "prog");
  GLADE_HOOKUP_OBJECT (Ajouter, autre, "autre");
  GLADE_HOOKUP_OBJECT (Ajouter, label95, "label95");
  GLADE_HOOKUP_OBJECT (Ajouter, Ajouter2, "Ajouter2");
  GLADE_HOOKUP_OBJECT (Ajouter, Annuler1, "Annuler1");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Ajouter, image14, "image14");
  GLADE_HOOKUP_OBJECT (Ajouter, label86, "label86");
  GLADE_HOOKUP_OBJECT (Ajouter, entry38, "entry38");
  GLADE_HOOKUP_OBJECT (Ajouter, label136, "label136");
  GLADE_HOOKUP_OBJECT (Ajouter, Homeajout, "Homeajout");
  GLADE_HOOKUP_OBJECT (Ajouter, image10, "image10");
  GLADE_HOOKUP_OBJECT (Ajouter, image31, "image31");

  return Ajouter;
}

GtkWidget*
create_Suppresion (void)
{
  GtkWidget *Suppresion;
  GtkWidget *fixed3;
  GtkWidget *entry_cinsup;
  GtkWidget *CIN;
  GtkWidget *Homesupp;
  GtkWidget *image8;
  GtkWidget *image23;
  GtkWidget *label109;
  GtkWidget *hseparator2;
  GtkWidget *hseparator3;
  GtkWidget *button1;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image22;
  GtkWidget *label108;
  GtkWidget *label125;
  GtkWidget *Annuler2;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image20;
  GtkWidget *label96;

  Suppresion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Suppresion), _("Suppresion"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Suppresion), fixed3);

  entry_cinsup = gtk_entry_new ();
  gtk_widget_show (entry_cinsup);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_cinsup, 104, 176);
  gtk_widget_set_size_request (entry_cinsup, 248, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cinsup), 8226);

  CIN = gtk_label_new (_("CIN"));
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed3), CIN, 48, 184);
  gtk_widget_set_size_request (CIN, 56, 17);

  Homesupp = gtk_button_new ();
  gtk_widget_show (Homesupp);
  gtk_fixed_put (GTK_FIXED (fixed3), Homesupp, 352, 352);
  gtk_widget_set_size_request (Homesupp, 96, 29);

  image8 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (Homesupp), image8);

  image23 = create_pixmap (Suppresion, "images.jpeg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed3), image23, 488, 96);
  gtk_widget_set_size_request (image23, 272, 280);

  label109 = gtk_label_new_with_mnemonic (_("<span color=\"purple\">Supprimer un etudiant</span>"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed3), label109, 176, 16);
  gtk_widget_set_size_request (label109, 368, 25);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator2, 128, 72);
  gtk_widget_set_size_request (hseparator2, 456, 16);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator3, 128, 72);
  gtk_widget_set_size_request (hseparator3, 16, 16);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed3), button1, 48, 352);
  gtk_widget_set_size_request (button1, 112, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button1), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox15), image22, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("<span color=\"red\">supprimer</span>"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox15), label108, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label108), TRUE);

  label125 = gtk_label_new ("");
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed3), label125, 40, 248);
  gtk_widget_set_size_request (label125, 352, 25);

  Annuler2 = gtk_button_new ();
  gtk_widget_show (Annuler2);
  gtk_fixed_put (GTK_FIXED (fixed3), Annuler2, 208, 352);
  gtk_widget_set_size_request (Annuler2, 96, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (Annuler2), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image20 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox13), image20, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox13), label96, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Homesupp, "clicked",
                    G_CALLBACK (on_Homesupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) Annuler2, "clicked",
                    G_CALLBACK (on_Annuler2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Suppresion, Suppresion, "Suppresion");
  GLADE_HOOKUP_OBJECT (Suppresion, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Suppresion, entry_cinsup, "entry_cinsup");
  GLADE_HOOKUP_OBJECT (Suppresion, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (Suppresion, Homesupp, "Homesupp");
  GLADE_HOOKUP_OBJECT (Suppresion, image8, "image8");
  GLADE_HOOKUP_OBJECT (Suppresion, image23, "image23");
  GLADE_HOOKUP_OBJECT (Suppresion, label109, "label109");
  GLADE_HOOKUP_OBJECT (Suppresion, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (Suppresion, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (Suppresion, button1, "button1");
  GLADE_HOOKUP_OBJECT (Suppresion, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Suppresion, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Suppresion, image22, "image22");
  GLADE_HOOKUP_OBJECT (Suppresion, label108, "label108");
  GLADE_HOOKUP_OBJECT (Suppresion, label125, "label125");
  GLADE_HOOKUP_OBJECT (Suppresion, Annuler2, "Annuler2");
  GLADE_HOOKUP_OBJECT (Suppresion, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Suppresion, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Suppresion, image20, "image20");
  GLADE_HOOKUP_OBJECT (Suppresion, label96, "label96");

  return Suppresion;
}

GtkWidget*
create_chercher (void)
{
  GtkWidget *chercher;
  GtkWidget *fixed4;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *entry15;
  GtkWidget *CIN;
  GtkWidget *entry16;
  GtkWidget *Homechercher;
  GtkWidget *image9;
  GtkWidget *entry17;
  GtkWidget *label105;
  GtkWidget *sexe;
  GtkWidget *entry18;
  GtkWidget *niveau;
  GtkWidget *prenom;
  GtkWidget *nom;
  GtkWidget *entry29;
  GtkWidget *label123;
  GtkWidget *merci;
  GtkWidget *image25;
  GtkWidget *entry30;
  GtkWidget *adresse;
  GtkWidget *label106;
  GtkWidget *entry35;
  GtkWidget *entry36;
  GtkWidget *ID;
  GtkWidget *label132;
  GtkWidget *label103;
  GtkWidget *button2;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image30;
  GtkWidget *label134;
  GtkWidget *hseparator1;
  GtkWidget *Annuler3;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image16;
  GtkWidget *label88;
  GtkWidget *label135;
  GtkWidget *chercher2;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image21;
  GtkWidget *label107;

  chercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chercher), _("chercher"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (chercher), fixed4);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed4), entry11, 216, 88);
  gtk_widget_set_size_request (entry11, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 184, 248);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed4), entry13, 616, 240);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed4), entry15, 184, 304);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  CIN = gtk_label_new (_("CIN"));
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed4), CIN, 40, 312);
  gtk_widget_set_size_request (CIN, 104, 25);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed4), entry16, 616, 296);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  Homechercher = gtk_button_new ();
  gtk_widget_show (Homechercher);
  gtk_fixed_put (GTK_FIXED (fixed4), Homechercher, 792, 16);
  gtk_widget_set_size_request (Homechercher, 66, 29);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (Homechercher), image9);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed4), entry17, 616, 352);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  label105 = gtk_label_new (_("Email"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed4), label105, 512, 360);
  gtk_widget_set_size_request (label105, 57, 17);

  sexe = gtk_label_new (_("Sexe"));
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixed4), sexe, 72, 360);
  gtk_widget_set_size_request (sexe, 57, 17);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed4), entry18, 184, 400);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  niveau = gtk_label_new (_("Niveau"));
  gtk_widget_show (niveau);
  gtk_fixed_put (GTK_FIXED (fixed4), niveau, 488, 304);
  gtk_widget_set_size_request (niveau, 112, 17);

  prenom = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), prenom, 488, 240);
  gtk_widget_set_size_request (prenom, 112, 25);

  nom = gtk_label_new (_("Nom"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed4), nom, 24, 248);
  gtk_widget_set_size_request (nom, 144, 25);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed4), entry29, 616, 400);
  gtk_widget_set_size_request (entry29, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  label123 = gtk_label_new (_("N\302\260 Telephone"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed4), label123, 504, 408);
  gtk_widget_set_size_request (label123, 113, 17);

  merci = gtk_label_new (_("Merci"));
  gtk_widget_show (merci);
  gtk_fixed_put (GTK_FIXED (fixed4), merci, 840, 472);
  gtk_widget_set_size_request (merci, 57, 17);

  image25 = create_pixmap (chercher, "depositphotos_191044362-stock-photo-mans-hands-and-man-looking.jpg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed4), image25, 792, 56);
  gtk_widget_set_size_request (image25, 488, 408);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed4), entry30, 184, 456);
  gtk_widget_set_size_request (entry30, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  adresse = gtk_label_new (_("adresse"));
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixed4), adresse, 72, 464);
  gtk_widget_set_size_request (adresse, 57, 17);

  label106 = gtk_label_new (_("Relev\303\251 du compte"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed4), label106, 32, 400);
  gtk_widget_set_size_request (label106, 128, 25);

  entry35 = gtk_entry_new ();
  gtk_widget_show (entry35);
  gtk_fixed_put (GTK_FIXED (fixed4), entry35, 184, 352);
  gtk_widget_set_size_request (entry35, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry35), 8226);

  entry36 = gtk_entry_new ();
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed4), entry36, 616, 464);
  gtk_widget_set_size_request (entry36, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry36), _("--/--/----"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  ID = gtk_label_new (_("ID a rechercher"));
  gtk_widget_show (ID);
  gtk_fixed_put (GTK_FIXED (fixed4), ID, 88, 96);
  gtk_widget_set_size_request (ID, 128, 17);

  label132 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed4), label132, 464, 464);
  gtk_widget_set_size_request (label132, 144, 25);

  label103 = gtk_label_new (_("<span color=\"red\"><b><u>BIENVENU \303\240 la recherche</u></b></span>"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed4), label103, 152, 16);
  gtk_widget_set_size_request (label103, 320, 31);
  gtk_label_set_use_markup (GTK_LABEL (label103), TRUE);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 576, 88);
  gtk_widget_set_size_request (button2, 104, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button2), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image30 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox17), image30, FALSE, FALSE, 0);

  label134 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label134);
  gtk_box_pack_start (GTK_BOX (hbox17), label134, FALSE, FALSE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator1, 128, 160);
  gtk_widget_set_size_request (hseparator1, 704, 16);

  Annuler3 = gtk_button_new ();
  gtk_widget_show (Annuler3);
  gtk_fixed_put (GTK_FIXED (fixed4), Annuler3, 688, 88);
  gtk_widget_set_size_request (Annuler3, 88, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (Annuler3), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image16 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox9), image16, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox9), label88, FALSE, FALSE, 0);

  label135 = gtk_label_new ("");
  gtk_widget_show (label135);
  gtk_fixed_put (GTK_FIXED (fixed4), label135, 208, 168);
  gtk_widget_set_size_request (label135, 472, 33);

  chercher2 = gtk_button_new ();
  gtk_widget_show (chercher2);
  gtk_fixed_put (GTK_FIXED (fixed4), chercher2, 432, 88);
  gtk_widget_set_size_request (chercher2, 120, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (chercher2), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image21 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox14), image21, FALSE, FALSE, 0);

  label107 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox14), label107, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Homechercher, "clicked",
                    G_CALLBACK (on_Homechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher2, "clicked",
                    G_CALLBACK (on_chercher2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chercher, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (chercher, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (chercher, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (chercher, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (chercher, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (chercher, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (chercher, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (chercher, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (chercher, Homechercher, "Homechercher");
  GLADE_HOOKUP_OBJECT (chercher, image9, "image9");
  GLADE_HOOKUP_OBJECT (chercher, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (chercher, label105, "label105");
  GLADE_HOOKUP_OBJECT (chercher, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (chercher, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (chercher, niveau, "niveau");
  GLADE_HOOKUP_OBJECT (chercher, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (chercher, nom, "nom");
  GLADE_HOOKUP_OBJECT (chercher, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (chercher, label123, "label123");
  GLADE_HOOKUP_OBJECT (chercher, merci, "merci");
  GLADE_HOOKUP_OBJECT (chercher, image25, "image25");
  GLADE_HOOKUP_OBJECT (chercher, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (chercher, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (chercher, label106, "label106");
  GLADE_HOOKUP_OBJECT (chercher, entry35, "entry35");
  GLADE_HOOKUP_OBJECT (chercher, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (chercher, ID, "ID");
  GLADE_HOOKUP_OBJECT (chercher, label132, "label132");
  GLADE_HOOKUP_OBJECT (chercher, label103, "label103");
  GLADE_HOOKUP_OBJECT (chercher, button2, "button2");
  GLADE_HOOKUP_OBJECT (chercher, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (chercher, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (chercher, image30, "image30");
  GLADE_HOOKUP_OBJECT (chercher, label134, "label134");
  GLADE_HOOKUP_OBJECT (chercher, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (chercher, Annuler3, "Annuler3");
  GLADE_HOOKUP_OBJECT (chercher, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (chercher, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (chercher, image16, "image16");
  GLADE_HOOKUP_OBJECT (chercher, label88, "label88");
  GLADE_HOOKUP_OBJECT (chercher, label135, "label135");
  GLADE_HOOKUP_OBJECT (chercher, chercher2, "chercher2");
  GLADE_HOOKUP_OBJECT (chercher, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (chercher, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (chercher, image21, "image21");
  GLADE_HOOKUP_OBJECT (chercher, label107, "label107");

  return chercher;
}

GtkWidget*
create_Afficher (void)
{
  GtkWidget *Afficher;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *homeafficher;
  GtkWidget *image11;
  GtkWidget *image33;
  GtkWidget *image27;

  Afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Afficher), _("Afficher"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Afficher), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 0, 240);
  gtk_widget_set_size_request (treeview1, 1296, 312);

  homeafficher = gtk_button_new ();
  gtk_widget_show (homeafficher);
  gtk_fixed_put (GTK_FIXED (fixed5), homeafficher, 1040, 184);
  gtk_widget_set_size_request (homeafficher, 66, 29);

  image11 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (homeafficher), image11);

  image33 = create_pixmap (Afficher, "download (1).jpeg");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed5), image33, 40, 0);
  gtk_widget_set_size_request (image33, 456, 232);

  image27 = create_pixmap (Afficher, "images (2).jpeg");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed5), image27, 560, 24);
  gtk_widget_set_size_request (image27, 288, 184);

  g_signal_connect ((gpointer) homeafficher, "clicked",
                    G_CALLBACK (on_homeafficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher, Afficher, "Afficher");
  GLADE_HOOKUP_OBJECT (Afficher, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Afficher, homeafficher, "homeafficher");
  GLADE_HOOKUP_OBJECT (Afficher, image11, "image11");
  GLADE_HOOKUP_OBJECT (Afficher, image33, "image33");
  GLADE_HOOKUP_OBJECT (Afficher, image27, "image27");

  return Afficher;
}

GtkWidget*
create_Dashboard (void)
{
  GtkWidget *Dashboard;
  GtkWidget *fixed8;
  GtkWidget *Homedash;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image12;
  GtkWidget *homedash;
  GtkWidget *Annuler5;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image18;
  GtkWidget *label90;
  GtkWidget *label147;
  GtkWidget *label148;
  GtkWidget *label146;
  GtkWidget *label145;
  GtkWidget *label140;
  GtkWidget *label141;
  GtkWidget *label142;
  GtkWidget *label143;
  GtkWidget *label144;
  GtkWidget *label149;

  Dashboard = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Dashboard), _("Dashboard"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Dashboard), fixed8);

  Homedash = gtk_button_new ();
  gtk_widget_show (Homedash);
  gtk_fixed_put (GTK_FIXED (fixed8), Homedash, 192, 72);
  gtk_widget_set_size_request (Homedash, 74, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (Homedash), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image12 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox6), image12, FALSE, FALSE, 0);

  homedash = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (homedash);
  gtk_box_pack_start (GTK_BOX (hbox6), homedash, FALSE, FALSE, 0);

  Annuler5 = gtk_button_new ();
  gtk_widget_show (Annuler5);
  gtk_fixed_put (GTK_FIXED (fixed8), Annuler5, 56, 96);
  gtk_widget_set_size_request (Annuler5, 104, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (Annuler5), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image18 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox11), image18, FALSE, FALSE, 0);

  label90 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox11), label90, FALSE, FALSE, 0);

  label147 = gtk_label_new (_("niveau3"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed8), label147, 48, 264);
  gtk_widget_set_size_request (label147, 81, 17);

  label148 = gtk_label_new (_("niveau4"));
  gtk_widget_show (label148);
  gtk_fixed_put (GTK_FIXED (fixed8), label148, 56, 296);
  gtk_widget_set_size_request (label148, 72, 17);

  label146 = gtk_label_new (_("niveau2"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed8), label146, 64, 232);
  gtk_widget_set_size_request (label146, 57, 17);

  label145 = gtk_label_new (_("niveau1"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed8), label145, 48, 208);
  gtk_widget_set_size_request (label145, 96, 17);

  label140 = gtk_label_new ("");
  gtk_widget_show (label140);
  gtk_fixed_put (GTK_FIXED (fixed8), label140, 232, 200);
  gtk_widget_set_size_request (label140, 152, 17);

  label141 = gtk_label_new ("");
  gtk_widget_show (label141);
  gtk_fixed_put (GTK_FIXED (fixed8), label141, 240, 232);
  gtk_widget_set_size_request (label141, 136, 17);

  label142 = gtk_label_new ("");
  gtk_widget_show (label142);
  gtk_fixed_put (GTK_FIXED (fixed8), label142, 240, 272);
  gtk_widget_set_size_request (label142, 136, 17);

  label143 = gtk_label_new ("");
  gtk_widget_show (label143);
  gtk_fixed_put (GTK_FIXED (fixed8), label143, 232, 304);
  gtk_widget_set_size_request (label143, 120, 17);

  label144 = gtk_label_new ("");
  gtk_widget_show (label144);
  gtk_fixed_put (GTK_FIXED (fixed8), label144, 248, 328);
  gtk_widget_set_size_request (label144, 120, 17);

  label149 = gtk_label_new (_("niveau5"));
  gtk_widget_show (label149);
  gtk_fixed_put (GTK_FIXED (fixed8), label149, 48, 329);
  gtk_widget_set_size_request (label149, 81, 16);

  g_signal_connect ((gpointer) Homedash, "clicked",
                    G_CALLBACK (on_Homedash_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Dashboard, Dashboard, "Dashboard");
  GLADE_HOOKUP_OBJECT (Dashboard, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Dashboard, Homedash, "Homedash");
  GLADE_HOOKUP_OBJECT (Dashboard, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Dashboard, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Dashboard, image12, "image12");
  GLADE_HOOKUP_OBJECT (Dashboard, homedash, "homedash");
  GLADE_HOOKUP_OBJECT (Dashboard, Annuler5, "Annuler5");
  GLADE_HOOKUP_OBJECT (Dashboard, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Dashboard, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Dashboard, image18, "image18");
  GLADE_HOOKUP_OBJECT (Dashboard, label90, "label90");
  GLADE_HOOKUP_OBJECT (Dashboard, label147, "label147");
  GLADE_HOOKUP_OBJECT (Dashboard, label148, "label148");
  GLADE_HOOKUP_OBJECT (Dashboard, label146, "label146");
  GLADE_HOOKUP_OBJECT (Dashboard, label145, "label145");
  GLADE_HOOKUP_OBJECT (Dashboard, label140, "label140");
  GLADE_HOOKUP_OBJECT (Dashboard, label141, "label141");
  GLADE_HOOKUP_OBJECT (Dashboard, label142, "label142");
  GLADE_HOOKUP_OBJECT (Dashboard, label143, "label143");
  GLADE_HOOKUP_OBJECT (Dashboard, label144, "label144");
  GLADE_HOOKUP_OBJECT (Dashboard, label149, "label149");

  return Dashboard;
}

GtkWidget*
create_Home (void)
{
  GtkWidget *Home;
  GtkWidget *fixed6;
  GtkWidget *WELCOME;
  GtkWidget *Annuler6;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image19;
  GtkWidget *label91;

  Home = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Home), _("Home"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Home), fixed6);

  WELCOME = gtk_label_new_with_mnemonic (_("<span color=\"purple\"> WELCOME </span>"));
  gtk_widget_show (WELCOME);
  gtk_fixed_put (GTK_FIXED (fixed6), WELCOME, 432, 16);
  gtk_widget_set_size_request (WELCOME, 360, 81);
  gtk_label_set_use_markup (GTK_LABEL (WELCOME), TRUE);

  Annuler6 = gtk_button_new ();
  gtk_widget_show (Annuler6);
  gtk_fixed_put (GTK_FIXED (fixed6), Annuler6, 192, 48);
  gtk_widget_set_size_request (Annuler6, 96, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (Annuler6), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image19 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox12), image19, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox12), label91, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Home, Home, "Home");
  GLADE_HOOKUP_OBJECT (Home, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Home, WELCOME, "WELCOME");
  GLADE_HOOKUP_OBJECT (Home, Annuler6, "Annuler6");
  GLADE_HOOKUP_OBJECT (Home, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Home, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Home, image19, "image19");
  GLADE_HOOKUP_OBJECT (Home, label91, "label91");

  return Home;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed9;
  GtkWidget *image29;
  GtkWidget *label133;
  GtkWidget *oksup;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window1), fixed9);

  image29 = create_pixmap (window1, "262232302_603658580855305_6775061233973614213_n.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed9), image29, 88, 24);
  gtk_widget_set_size_request (image29, 176, 177);

  label133 = gtk_label_new (_("<span color=\"red\"><u>Suppression non effectu\303\251e</u></span>"));
  gtk_widget_show (label133);
  gtk_fixed_put (GTK_FIXED (fixed9), label133, 64, 216);
  gtk_widget_set_size_request (label133, 224, 25);
  gtk_label_set_use_markup (GTK_LABEL (label133), TRUE);

  oksup = gtk_button_new_with_mnemonic (_("ok"));
  gtk_widget_show (oksup);
  gtk_fixed_put (GTK_FIXED (fixed9), oksup, 120, 280);
  gtk_widget_set_size_request (oksup, 96, 29);

  g_signal_connect ((gpointer) oksup, "clicked",
                    G_CALLBACK (on_oksup_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window1, image29, "image29");
  GLADE_HOOKUP_OBJECT (window1, label133, "label133");
  GLADE_HOOKUP_OBJECT (window1, oksup, "oksup");

  return window1;
}

GtkWidget*
create_Authentification_foyer (void)
{
  GtkWidget *Authentification_foyer;
  GtkWidget *fixed10;
  GtkWidget *cinfoyer;
  GtkWidget *passfoyer;
  GtkWidget *button3;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image32;
  GtkWidget *label139;
  GtkWidget *label138;
  GtkWidget *label137;
  GtkWidget *image36;
  GtkWidget *image35;

  Authentification_foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Authentification_foyer), _("Log in"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (Authentification_foyer), fixed10);

  cinfoyer = gtk_entry_new ();
  gtk_widget_show (cinfoyer);
  gtk_fixed_put (GTK_FIXED (fixed10), cinfoyer, 216, 232);
  gtk_widget_set_size_request (cinfoyer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinfoyer), 8226);

  passfoyer = gtk_entry_new ();
  gtk_widget_show (passfoyer);
  gtk_fixed_put (GTK_FIXED (fixed10), passfoyer, 216, 288);
  gtk_widget_set_size_request (passfoyer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (passfoyer), 8226);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed10), button3, 232, 368);
  gtk_widget_set_size_request (button3, 120, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button3), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image32 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox18), image32, FALSE, FALSE, 0);

  label139 = gtk_label_new_with_mnemonic (_("Connexion"));
  gtk_widget_show (label139);
  gtk_box_pack_start (GTK_BOX (hbox18), label139, FALSE, FALSE, 0);

  label138 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed10), label138, 56, 288);
  gtk_widget_set_size_request (label138, 104, 17);

  label137 = gtk_label_new (_("CIN"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed10), label137, 64, 232);
  gtk_widget_set_size_request (label137, 57, 17);

  image36 = create_pixmap (Authentification_foyer, "download (2).jpeg");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed10), image36, 56, 0);
  gtk_widget_set_size_request (image36, 496, 216);

  image35 = create_pixmap (Authentification_foyer, "8a99e4e3e5ff81c9540507453d382c4b--foyer-ideas-teacher.jpg");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed10), image35, 360, 136);
  gtk_widget_set_size_request (image35, 368, 320);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Authentification_foyer, Authentification_foyer, "Authentification_foyer");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, cinfoyer, "cinfoyer");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, passfoyer, "passfoyer");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, button3, "button3");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, image32, "image32");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, label139, "label139");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, label138, "label138");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, label137, "label137");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, image36, "image36");
  GLADE_HOOKUP_OBJECT (Authentification_foyer, image35, "image35");

  return Authentification_foyer;
}

